[profile.default]
solc-version = '0.8.28'
src = 'contracts/ERC20'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
optimizer = true
optimizer_runs = 1  # Adjust the number of runs to fit your needs
via_ir = true

libs = [
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@layerzerolabs/onft-evm/=node_modules/@layerzerolabs/onft-evm/',
    '@layerzerolabs/oapp-evm/=node_modules/@layerzerolabs/oapp-evm/',
]

[fuzz]
runs = 5000
max_test_rejects = 0
show_logs = true



